<?php
if (!defined('_VALID_TCPRO')) exit ('No direct access allowed!');
/**
 * timezones_inc.php
 * 
 * Declaration of timezones
 * 
 * @package TeamCalPro
 * @version 3.6.020 
 * @author George Lewe <george@lewe.com>
 * @copyright Copyright (c) 2004-2015 by George Lewe
 * @link http://www.lewe.com
 * @license http://tcpro.lewe.com/doc/license.txt Based on GNU Public License v3
 */

/**
 * Global variable declaration of timezones
 * 
 * @global array $timezone 
 */ 
$timezone = array (           
"Africa/Abidjan" => array ("name" => "Africa/Abidjan" , "country" => "CI" , "latitude" => "+0519" , "longitude" => "-00402" , "comment" => "" ),
"Africa/Accra" => array ("name" => "Africa/Accra" , "country" => "GH" , "latitude" => "+0533" , "longitude" => "-00013" , "comment" => "" ),
"Africa/Addis_Ababa" => array ("name" => "Africa/Addis_Ababa" , "country" => "ET" , "latitude" => "+0902" , "longitude" => "+03842" , "comment" => "" ),
"Africa/Algiers" => array ("name" => "Africa/Algiers" , "country" => "DZ" , "latitude" => "+3647" , "longitude" => "+00303" , "comment" => "" ),
"Africa/Asmera" => array ("name" => "Africa/Asmera" , "country" => "ER" , "latitude" => "+1520" , "longitude" => "+03853" , "comment" => "" ),
"Africa/Bamako" => array ("name" => "Africa/Bamako" , "country" => "ML" , "latitude" => "+1239" , "longitude" => "-00800" , "comment" => "southwest Mali" ),
"Africa/Bangui" => array ("name" => "Africa/Bangui" , "country" => "CF" , "latitude" => "+0422" , "longitude" => "+01835" , "comment" => "" ),
"Africa/Banjul" => array ("name" => "Africa/Banjul" , "country" => "GM" , "latitude" => "+1328" , "longitude" => "-01639" , "comment" => "" ),
"Africa/Bissau" => array ("name" => "Africa/Bissau" , "country" => "GW" , "latitude" => "+1151" , "longitude" => "-01535" , "comment" => "" ),
"Africa/Blantyre" => array ("name" => "Africa/Blantyre" , "country" => "MW" , "latitude" => "-1547" , "longitude" => "+03500" , "comment" => "" ),
"Africa/Brazzaville" => array ("name" => "Africa/Brazzaville" , "country" => "CG" , "latitude" => "-0416" , "longitude" => "+01517" , "comment" => "" ),
"Africa/Bujumbura" => array ("name" => "Africa/Bujumbura" , "country" => "BI" , "latitude" => "-0323" , "longitude" => "+02922" , "comment" => "" ),
"Africa/Cairo" => array ("name" => "Africa/Cairo" , "country" => "EG" , "latitude" => "+3003" , "longitude" => "+03115" , "comment" => "" ),
"Africa/Casablanca" => array ("name" => "Africa/Casablanca" , "country" => "MA" , "latitude" => "+3339" , "longitude" => "-00735" , "comment" => "" ),
"Africa/Ceuta" => array ("name" => "Africa/Ceuta" , "country" => "ES" , "latitude" => "+3553" , "longitude" => "-00519" , "comment" => "Ceuta & Melilla" ),
"Africa/Conakry" => array ("name" => "Africa/Conakry" , "country" => "GN" , "latitude" => "+0931" , "longitude" => "-01343" , "comment" => "" ),
"Africa/Dakar" => array ("name" => "Africa/Dakar" , "country" => "SN" , "latitude" => "+1440" , "longitude" => "-01726" , "comment" => "" ),
"Africa/Dar_es_Salaam" => array ("name" => "Africa/Dar_es_Salaam" , "country" => "TZ" , "latitude" => "-0648" , "longitude" => "+03917" , "comment" => "" ),
"Africa/Djibouti" => array ("name" => "Africa/Djibouti" , "country" => "DJ" , "latitude" => "+1136" , "longitude" => "+04309" , "comment" => "" ),
"Africa/Douala" => array ("name" => "Africa/Douala" , "country" => "CM" , "latitude" => "+0403" , "longitude" => "+00942" , "comment" => "" ),
"Africa/El_Aaiun" => array ("name" => "Africa/El_Aaiun" , "country" => "EH" , "latitude" => "+2709" , "longitude" => "-01312" , "comment" => "" ),
"Africa/Freetown" => array ("name" => "Africa/Freetown" , "country" => "SL" , "latitude" => "+0830" , "longitude" => "-01315" , "comment" => "" ),
"Africa/Gaborone" => array ("name" => "Africa/Gaborone" , "country" => "BW" , "latitude" => "-2545" , "longitude" => "+02555" , "comment" => "" ),
"Africa/Harare" => array ("name" => "Africa/Harare" , "country" => "ZW" , "latitude" => "-1750" , "longitude" => "+03103" , "comment" => "" ),
"Africa/Johannesburg" => array ("name" => "Africa/Johannesburg" , "country" => "ZA" , "latitude" => "-2615" , "longitude" => "+02800" , "comment" => "" ),
"Africa/Kampala" => array ("name" => "Africa/Kampala" , "country" => "UG" , "latitude" => "+0019" , "longitude" => "+03225" , "comment" => "" ),
"Africa/Khartoum" => array ("name" => "Africa/Khartoum" , "country" => "SD" , "latitude" => "+1536" , "longitude" => "+03232" , "comment" => "" ),
"Africa/Kigali" => array ("name" => "Africa/Kigali" , "country" => "RW" , "latitude" => "-0157" , "longitude" => "+03004" , "comment" => "" ),
"Africa/Kinshasa" => array ("name" => "Africa/Kinshasa" , "country" => "CD" , "latitude" => "-0418" , "longitude" => "+01518" , "comment" => "west Dem. Rep. of Congo" ),
"Africa/Lagos" => array ("name" => "Africa/Lagos" , "country" => "NG" , "latitude" => "+0627" , "longitude" => "+00324" , "comment" => "" ),
"Africa/Libreville" => array ("name" => "Africa/Libreville" , "country" => "GA" , "latitude" => "+0023" , "longitude" => "+00927" , "comment" => "" ),
"Africa/Lome" => array ("name" => "Africa/Lome" , "country" => "TG" , "latitude" => "+0608" , "longitude" => "+00113" , "comment" => "" ),
"Africa/Luanda" => array ("name" => "Africa/Luanda" , "country" => "AO" , "latitude" => "-0848" , "longitude" => "+01314" , "comment" => "" ),
"Africa/Lubumbashi" => array ("name" => "Africa/Lubumbashi" , "country" => "CD" , "latitude" => "-1140" , "longitude" => "+02728" , "comment" => "east Dem. Rep. of Congo" ),
"Africa/Lusaka" => array ("name" => "Africa/Lusaka" , "country" => "ZM" , "latitude" => "-1525" , "longitude" => "+02817" , "comment" => "" ),
"Africa/Malabo" => array ("name" => "Africa/Malabo" , "country" => "GQ" , "latitude" => "+0345" , "longitude" => "+00847" , "comment" => "" ),
"Africa/Maputo" => array ("name" => "Africa/Maputo" , "country" => "MZ" , "latitude" => "-2558" , "longitude" => "+03235" , "comment" => "" ),
"Africa/Maseru" => array ("name" => "Africa/Maseru" , "country" => "LS" , "latitude" => "-2928" , "longitude" => "+02730" , "comment" => "" ),
"Africa/Mbabane" => array ("name" => "Africa/Mbabane" , "country" => "SZ" , "latitude" => "-2618" , "longitude" => "+03106" , "comment" => "" ),
"Africa/Mogadishu" => array ("name" => "Africa/Mogadishu" , "country" => "SO" , "latitude" => "+0204" , "longitude" => "+04522" , "comment" => "" ),
"Africa/Monrovia" => array ("name" => "Africa/Monrovia" , "country" => "LR" , "latitude" => "+0618" , "longitude" => "-01047" , "comment" => "" ),
"Africa/Nairobi" => array ("name" => "Africa/Nairobi" , "country" => "KE" , "latitude" => "-0117" , "longitude" => "+03649" , "comment" => "" ),
"Africa/Ndjamena" => array ("name" => "Africa/Ndjamena" , "country" => "TD" , "latitude" => "+1207" , "longitude" => "+01503" , "comment" => "" ),
"Africa/Niamey" => array ("name" => "Africa/Niamey" , "country" => "NE" , "latitude" => "+1331" , "longitude" => "+00207" , "comment" => "" ),
"Africa/Nouakchott" => array ("name" => "Africa/Nouakchott" , "country" => "MR" , "latitude" => "+1806" , "longitude" => "-01557" , "comment" => "" ),
"Africa/Ouagadougou" => array ("name" => "Africa/Ouagadougou" , "country" => "BF" , "latitude" => "+1222" , "longitude" => "-00131" , "comment" => "" ),
"Africa/Porto/Novo" => array ("name" => "Africa/Porto/Novo" , "country" => "BJ" , "latitude" => "+0629" , "longitude" => "+00237" , "comment" => "" ),
"Africa/Sao_Tome" => array ("name" => "Africa/Sao_Tome" , "country" => "ST" , "latitude" => "+0020" , "longitude" => "+00644" , "comment" => "" ),
"Africa imbuktu" => array ("name" => "Africa imbuktu" , "country" => "ML" , "latitude" => "+1446" , "longitude" => "-00301" , "comment" => "northeast Mali" ),
"Africa ripoli" => array ("name" => "Africa ripoli" , "country" => "LY" , "latitude" => "+3254" , "longitude" => "+01311" , "comment" => "" ),
"Africa unis" => array ("name" => "Africa unis" , "country" => "TN" , "latitude" => "+3648" , "longitude" => "+01011" , "comment" => "" ),
"Africa/Windhoek" => array ("name" => "Africa/Windhoek" , "country" => "NA" , "latitude" => "-2234" , "longitude" => "+01706" , "comment" => "" ),
"America/Adak" => array ("name" => "America/Adak" , "country" => "US" , "latitude" => "+51524" , "longitude" => "-1763929" , "comment" => "Aleutian Islands" ),
"America/Anchorage" => array ("name" => "America/Anchorage" , "country" => "US" , "latitude" => "+61130" , "longitude" => "-1495401" , "comment" => "Alaska Time" ),
"America/Anguilla" => array ("name" => "America/Anguilla" , "country" => "AI" , "latitude" => "+1812" , "longitude" => "-06304" , "comment" => "" ),
"America/Antigua" => array ("name" => "America/Antigua" , "country" => "AG" , "latitude" => "+1703" , "longitude" => "-06148" , "comment" => "" ),
"America/Araguaina" => array ("name" => "America/Araguaina" , "country" => "BR" , "latitude" => "-0712" , "longitude" => "-04812" , "comment" => "Tocantins" ),
"America/Aruba" => array ("name" => "America/Aruba" , "country" => "AW" , "latitude" => "+1230" , "longitude" => "-06858" , "comment" => "" ),
"America/Asuncion" => array ("name" => "America/Asuncion" , "country" => "PY" , "latitude" => "-2516" , "longitude" => "-05740" , "comment" => "" ),
"America/Barbados" => array ("name" => "America/Barbados" , "country" => "BB" , "latitude" => "+1306" , "longitude" => "-05937" , "comment" => "" ),
"America/Belem" => array ("name" => "America/Belem" , "country" => "BR" , "latitude" => "-0127" , "longitude" => "-04829" , "comment" => "Amapa, E Para" ),
"America/Belize" => array ("name" => "America/Belize" , "country" => "BZ" , "latitude" => "+1730" , "longitude" => "-08812" , "comment" => "" ),
"America/Bogota" => array ("name" => "America/Bogota" , "country" => "CO" , "latitude" => "+0436" , "longitude" => "-07405" , "comment" => "" ),
"America/Boise" => array ("name" => "America/Boise" , "country" => "US" , "latitude" => "+43364" , "longitude" => "-1161209" , "comment" => "Mountain Time - south Idaho & east Oregon" ),
"America/Buenos_Aires" => array ("name" => "America/Buenos_Aires" , "country" => "AR" , "latitude" => "-3436" , "longitude" => "-05827" , "comment" => "E Argentina (BA, DF, SC, TF)" ),
"America/Cancun" => array ("name" => "America/Cancun" , "country" => "MX" , "latitude" => "+2105" , "longitude" => "-08646" , "comment" => "Eastern Time" ),
"America/Caracas" => array ("name" => "America/Caracas" , "country" => "VE" , "latitude" => "+1030" , "longitude" => "-06656" , "comment" => "" ),
"America/Catamarca" => array ("name" => "America/Catamarca" , "country" => "AR" , "latitude" => "-2828" , "longitude" => "-06547" , "comment" => "Catamarca (CT)" ),
"America/Cayenne" => array ("name" => "America/Cayenne" , "country" => "GF" , "latitude" => "+0456" , "longitude" => "-05220" , "comment" => "" ),
"America/Cayman" => array ("name" => "America/Cayman" , "country" => "KY" , "latitude" => "+1918" , "longitude" => "-08123" , "comment" => "" ),
"America/Chicago" => array ("name" => "America/Chicago" , "country" => "US" , "latitude" => "+41510" , "longitude" => "-0873900" , "comment" => "Central Time" ),
"America/Chihuahua" => array ("name" => "America/Chihuahua" , "country" => "MX" , "latitude" => "+2838" , "longitude" => "-10605" , "comment" => "Mountain Time - Chihuahua" ),
"America/Cordoba" => array ("name" => "America/Cordoba" , "country" => "AR" , "latitude" => "-3124" , "longitude" => "-06411" , "comment" => "W Argentina (CB, SA, TM, LR, SJ, SL, NQ, RN)" ),
"America/Costa_Rica" => array ("name" => "America/Costa_Rica" , "country" => "CR" , "latitude" => "+0956" , "longitude" => "-08405" , "comment" => "" ),
"America/Cuiaba" => array ("name" => "America/Cuiaba" , "country" => "BR" , "latitude" => "-1535" , "longitude" => "-05605" , "comment" => "Mato Grosso, Mato Grosso do Sul" ),
"America/Curacao" => array ("name" => "America/Curacao" , "country" => "AN" , "latitude" => "+1211" , "longitude" => "-06900" , "comment" => "" ),
"America/Dawson_Creek" => array ("name" => "America/Dawson_Creek" , "country" => "CA" , "latitude" => "+5946" , "longitude" => "-12014" , "comment" => "Mountain Standard Time - Dawson Creek & Fort Saint John, British Columbia" ),
"America/Dawson" => array ("name" => "America/Dawson" , "country" => "CA" , "latitude" => "+6404" , "longitude" => "-13925" , "comment" => "Pacific Time - north Yukon" ),
"America/Denver" => array ("name" => "America/Denver" , "country" => "US" , "latitude" => "+39442" , "longitude" => "-1045903" , "comment" => "Mountain Time" ),
"America/Detroit" => array ("name" => "America/Detroit" , "country" => "US" , "latitude" => "+42195" , "longitude" => "-0830245" , "comment" => "Eastern Time - Michigan - most locations" ),
"America/Dominica" => array ("name" => "America/Dominica" , "country" => "DM" , "latitude" => "+1518" , "longitude" => "-06124" , "comment" => "" ),
"America/Edmonton" => array ("name" => "America/Edmonton" , "country" => "CA" , "latitude" => "+5333" , "longitude" => "-11328" , "comment" => "Mountain Time - Alberta, east British Columbia & west Saskatchewan" ),
"America/El_Salvador" => array ("name" => "America/El_Salvador" , "country" => "SV" , "latitude" => "+1342" , "longitude" => "-08912" , "comment" => "" ),
"America/Ensenada" => array ("name" => "America/Ensenada" , "country" => "MX" , "latitude" => "+3152" , "longitude" => "-11637" , "comment" => "Pacific Time - most locations" ),
"America/Fortaleza" => array ("name" => "America/Fortaleza" , "country" => "BR" , "latitude" => "-0343" , "longitude" => "-03830" , "comment" => "NE Brazil (MA, PI, CE, RN, PR, PE)" ),
"America/Glace_Bay" => array ("name" => "America/Glace_Bay" , "country" => "CA" , "latitude" => "+4612" , "longitude" => "-05957" , "comment" => "Atlantic Time - Nova Scotia - places that did not observe DST 1966-1971" ),
"America/Godthab" => array ("name" => "America/Godthab" , "country" => "GL" , "latitude" => "+6411" , "longitude" => "-05144" , "comment" => "southwest Greenland" ),
"America/Goose_Bay" => array ("name" => "America/Goose_Bay" , "country" => "CA" , "latitude" => "+5320" , "longitude" => "-06025" , "comment" => "Atlantic Time - E Labrador" ),
"America/Grand_Turk" => array ("name" => "America/Grand_Turk" , "country" => "TC" , "latitude" => "+2128" , "longitude" => "-07108" , "comment" => "" ),
"America/Grenada" => array ("name" => "America/Grenada" , "country" => "GD" , "latitude" => "+1203" , "longitude" => "-06145" , "comment" => "" ),
"America/Guadeloupe" => array ("name" => "America/Guadeloupe" , "country" => "GP" , "latitude" => "+1614" , "longitude" => "-06132" , "comment" => "" ),
"America/Guatemala" => array ("name" => "America/Guatemala" , "country" => "GT" , "latitude" => "+1438" , "longitude" => "-09031" , "comment" => "" ),
"America/Guayaquil" => array ("name" => "America/Guayaquil" , "country" => "EC" , "latitude" => "-0210" , "longitude" => "-07950" , "comment" => "mainland" ),
"America/Guyana" => array ("name" => "America/Guyana" , "country" => "GY" , "latitude" => "+0648" , "longitude" => "-05810" , "comment" => "" ),
"America/Halifax" => array ("name" => "America/Halifax" , "country" => "CA" , "latitude" => "+4439" , "longitude" => "-06336" , "comment" => "Atlantic Time - Nova Scotia (most places), NB, W Labrador, E Quebec & PEI" ),
"America/Havana" => array ("name" => "America/Havana" , "country" => "CU" , "latitude" => "+2308" , "longitude" => "-08222" , "comment" => "" ),
"America/Indiana/Knox" => array ("name" => "America/Indiana/Knox" , "country" => "US" , "latitude" => "+41174" , "longitude" => "-0863730" , "comment" => "Eastern Standard Time - Indiana - Starke County" ),
"America/Indiana/Marengo" => array ("name" => "America/Indiana/Marengo" , "country" => "US" , "latitude" => "+38223" , "longitude" => "-0862041" , "comment" => "Eastern Standard Time - Indiana - Crawford County" ),
"America/Indiana/Vevay" => array ("name" => "America/Indiana/Vevay" , "country" => "US" , "latitude" => "+38445" , "longitude" => "-0850402" , "comment" => "Eastern Standard Time - Indiana - Switzerland County" ),
"America/Indianapolis" => array ("name" => "America/Indianapolis" , "country" => "US" , "latitude" => "+39460" , "longitude" => "-0860929" , "comment" => "Eastern Standard Time - Indiana - most locations" ),
"America/Inuvik" => array ("name" => "America/Inuvik" , "country" => "CA" , "latitude" => "+6825" , "longitude" => "-11330" , "comment" => "Mountain Time - west Northwest Territories" ),
"America/Iqaluit" => array ("name" => "America/Iqaluit" , "country" => "CA" , "latitude" => "+6344" , "longitude" => "-06828" , "comment" => "Eastern Time - Northwest Territories" ),
"America/Jamaica" => array ("name" => "America/Jamaica" , "country" => "JM" , "latitude" => "+1800" , "longitude" => "-07648" , "comment" => "" ),
"America/Jujuy" => array ("name" => "America/Jujuy" , "country" => "AR" , "latitude" => "-2411" , "longitude" => "-06518" , "comment" => "Jujuy (JY)" ),
"America/Juneau" => array ("name" => "America/Juneau" , "country" => "US" , "latitude" => "+58180" , "longitude" => "-1342511" , "comment" => "Alaska Time - Alaska panhandle" ),
"America/La_Paz" => array ("name" => "America/La_Paz" , "country" => "BO" , "latitude" => "-1630" , "longitude" => "-06809" , "comment" => "" ),
"America/Lima" => array ("name" => "America/Lima" , "country" => "PE" , "latitude" => "-1203" , "longitude" => "-07703" , "comment" => "" ),
"America/Los_Angeles" => array ("name" => "America/Los_Angeles" , "country" => "US" , "latitude" => "+34030" , "longitude" => "-1181434" , "comment" => "Pacific Time" ),
"America/Louisville" => array ("name" => "America/Louisville" , "country" => "US" , "latitude" => "+38151" , "longitude" => "-0854534" , "comment" => "Eastern Time - Louisville, Kentucky" ),
"America/Maceio" => array ("name" => "America/Maceio" , "country" => "BR" , "latitude" => "-0940" , "longitude" => "-03543" , "comment" => "Alagoas, Sergipe" ),
"America/Managua" => array ("name" => "America/Managua" , "country" => "NI" , "latitude" => "+1209" , "longitude" => "-08617" , "comment" => "" ),
"America/Manaus" => array ("name" => "America/Manaus" , "country" => "BR" , "latitude" => "-0308" , "longitude" => "-06001" , "comment" => "Amazonas" ),
"America/Martinique" => array ("name" => "America/Martinique" , "country" => "MQ" , "latitude" => "+1436" , "longitude" => "-06105" , "comment" => "" ),
"America/Mazatlan" => array ("name" => "America/Mazatlan" , "country" => "MX" , "latitude" => "+2313" , "longitude" => "-10625" , "comment" => "Mountain Time - most locations" ),
"America/Mendoza" => array ("name" => "America/Mendoza" , "country" => "AR" , "latitude" => "-3253" , "longitude" => "-06849" , "comment" => "Mendoza (MZ)" ),
"America/Menominee" => array ("name" => "America/Menominee" , "country" => "US" , "latitude" => "+45062" , "longitude" => "-0873651" , "comment" => "Central Time - Michigan - Wisconsin border" ),
"America/Mexico_City" => array ("name" => "America/Mexico_City" , "country" => "MX" , "latitude" => "+1924" , "longitude" => "-09909" , "comment" => "Central Time" ),
"America/Miquelon" => array ("name" => "America/Miquelon" , "country" => "PM" , "latitude" => "+4703" , "longitude" => "-05620" , "comment" => "" ),
"America/Montevideo" => array ("name" => "America/Montevideo" , "country" => "UY" , "latitude" => "-3453" , "longitude" => "-05611" , "comment" => "" ),
"America/Montreal" => array ("name" => "America/Montreal" , "country" => "CA" , "latitude" => "+4531" , "longitude" => "-07334" , "comment" => "Eastern Time - Ontario & Quebec - most locations" ),
"America/Montserrat" => array ("name" => "America/Montserrat" , "country" => "MS" , "latitude" => "+1644" , "longitude" => "-06213" , "comment" => "" ),
"America/Nassau" => array ("name" => "America/Nassau" , "country" => "BS" , "latitude" => "+2505" , "longitude" => "-07721" , "comment" => "" ),
"America/New_York" => array ("name" => "America/New_York" , "country" => "US" , "latitude" => "+40425" , "longitude" => "-0740023" , "comment" => "Eastern Time" ),
"America/Nipigon" => array ("name" => "America/Nipigon" , "country" => "CA" , "latitude" => "+4901" , "longitude" => "-08816" , "comment" => "Eastern Time - Ontario & Quebec - places that did not observe DST 1967-1973" ),
"America/Nome" => array ("name" => "America/Nome" , "country" => "US" , "latitude" => "+64300" , "longitude" => "-1652423" , "comment" => "Alaska Time - west Alaska" ),
"America/Noronha" => array ("name" => "America/Noronha" , "country" => "BR" , "latitude" => "-0351" , "longitude" => "-03225" , "comment" => "Fernando de Noronha" ),
"America/Panama" => array ("name" => "America/Panama" , "country" => "PA" , "latitude" => "+0858" , "longitude" => "-07932" , "comment" => "" ),
"America/Pangnirtung" => array ("name" => "America/Pangnirtung" , "country" => "CA" , "latitude" => "+6608" , "longitude" => "-06544" , "comment" => "Atlantic Time - Northwest Territories" ),
"America/Paramaribo" => array ("name" => "America/Paramaribo" , "country" => "SR" , "latitude" => "+0550" , "longitude" => "-05510" , "comment" => "" ),
"America/Phoenix" => array ("name" => "America/Phoenix" , "country" => "US" , "latitude" => "+33265" , "longitude" => "-1120424" , "comment" => "Mountain Standard Time - Arizona" ),
"America/Port_of_Spain" => array ("name" => "America/Port_of_Spain" , "country" => "TT" , "latitude" => "+1039" , "longitude" => "-06131" , "comment" => "" ),
"America/Port/au/Prince" => array ("name" => "America/Port/au/Prince" , "country" => "HT" , "latitude" => "+1832" , "longitude" => "-07220" , "comment" => "" ),
"America/Porto_Acre" => array ("name" => "America/Porto_Acre" , "country" => "BR" , "latitude" => "-0934" , "longitude" => "-06731" , "comment" => "Acre" ),
"America/Porto_Velho" => array ("name" => "America/Porto_Velho" , "country" => "BR" , "latitude" => "-0846" , "longitude" => "-06354" , "comment" => "W Para, Rondonia, Roraima" ),
"America/Puerto_Rico" => array ("name" => "America/Puerto_Rico" , "country" => "PR" , "latitude" => "+18280" , "longitude" => "-0660622" , "comment" => "" ),
"America/Rainy_River" => array ("name" => "America/Rainy_River" , "country" => "CA" , "latitude" => "+4843" , "longitude" => "-09429" , "comment" => "Central Time - Rainy River & Fort Frances, Ontario" ),
"America/Rankin_Inlet" => array ("name" => "America/Rankin_Inlet" , "country" => "CA" , "latitude" => "+6245" , "longitude" => "-09210" , "comment" => "Central Time - Northwest Territories" ),
"America/Regina" => array ("name" => "America/Regina" , "country" => "CA" , "latitude" => "+5024" , "longitude" => "-10439" , "comment" => "Central Standard Time - Saskatchewan - most locations" ),
"America/Rosario" => array ("name" => "America/Rosario" , "country" => "AR" , "latitude" => "-3257" , "longitude" => "-06040" , "comment" => "NE Argentina (SF, ER, CN, MN, CC, FM, LP, CH)" ),
"America/Santiago" => array ("name" => "America/Santiago" , "country" => "CL" , "latitude" => "-3327" , "longitude" => "-07040" , "comment" => "mainland" ),
"America/Santo_Domingo" => array ("name" => "America/Santo_Domingo" , "country" => "DO" , "latitude" => "+1828" , "longitude" => "-06954" , "comment" => "" ),
"America/Sao_Paulo" => array ("name" => "America/Sao_Paulo" , "country" => "BR" , "latitude" => "-2332" , "longitude" => "-04637" , "comment" => "S & SE Brazil (BA, GO, DF, MG, ES, RJ, SP, PR, SC, RS)" ),
"America/Scoresbysund" => array ("name" => "America/Scoresbysund" , "country" => "GL" , "latitude" => "+7030" , "longitude" => "-02215" , "comment" => "east Greenland" ),
"America/Shiprock" => array ("name" => "America/Shiprock" , "country" => "US" , "latitude" => "+36470" , "longitude" => "-1084111" , "comment" => "Mountain Time - Navajo" ),
"America/St_Johns" => array ("name" => "America/St_Johns" , "country" => "CA" , "latitude" => "+4734" , "longitude" => "-05243" , "comment" => "Newfoundland Island" ),
"America/St_Kitts" => array ("name" => "America/St_Kitts" , "country" => "KN" , "latitude" => "+1718" , "longitude" => "-06243" , "comment" => "" ),
"America/St_Lucia" => array ("name" => "America/St_Lucia" , "country" => "LC" , "latitude" => "+1401" , "longitude" => "-06100" , "comment" => "" ),
"America/St_Thomas" => array ("name" => "America/St_Thomas" , "country" => "VI" , "latitude" => "+1821" , "longitude" => "-06456" , "comment" => "" ),
"America/St_Vincent" => array ("name" => "America/St_Vincent" , "country" => "VC" , "latitude" => "+1309" , "longitude" => "-06114" , "comment" => "" ),
"America/Swift_Current" => array ("name" => "America/Swift_Current" , "country" => "CA" , "latitude" => "+5017" , "longitude" => "-10750" , "comment" => "Central Standard Time - Saskatchewan - midwest" ),
"America egucigalpa" => array ("name" => "America egucigalpa" , "country" => "HN" , "latitude" => "+1406" , "longitude" => "-08713" , "comment" => "" ),
"America hule" => array ("name" => "America hule" , "country" => "GL" , "latitude" => "+7634" , "longitude" => "-06847" , "comment" => "northwest Greenland" ),
"America hunder_Bay" => array ("name" => "America hunder_Bay" , "country" => "CA" , "latitude" => "+4823" , "longitude" => "-08915" , "comment" => "Eastern Time - Thunder Bay, Ontario" ),
"America ijuana" => array ("name" => "America ijuana" , "country" => "MX" , "latitude" => "+3232" , "longitude" => "-11701" , "comment" => "Pacific Time - north Baja California" ),
"America ortola" => array ("name" => "America ortola" , "country" => "VG" , "latitude" => "+1827" , "longitude" => "-06437" , "comment" => "" ),
"America/Vancouver" => array ("name" => "America/Vancouver" , "country" => "CA" , "latitude" => "+4916" , "longitude" => "-12307" , "comment" => "Pacific Time - west British Columbia" ),
"America/Whitehorse" => array ("name" => "America/Whitehorse" , "country" => "CA" , "latitude" => "+6043" , "longitude" => "-13503" , "comment" => "Pacific Time - south Yukon" ),
"America/Winnipeg" => array ("name" => "America/Winnipeg" , "country" => "CA" , "latitude" => "+4953" , "longitude" => "-09709" , "comment" => "Central Time - Manitoba & west Ontario" ),
"America/Yakutat" => array ("name" => "America/Yakutat" , "country" => "US" , "latitude" => "+59324" , "longitude" => "-1394338" , "comment" => "Alaska Time - Alaska panhandle neck" ),
"America/Yellowknife" => array ("name" => "America/Yellowknife" , "country" => "CA" , "latitude" => "+6227" , "longitude" => "-11421" , "comment" => "Mountain Time - central Northwest Territories" ),
"Antarctica/Casey" => array ("name" => "Antarctica/Casey" , "country" => "AQ" , "latitude" => "-6617" , "longitude" => "+11031" , "comment" => "Casey Station, Bailey Peninsula" ),
"Antarctica/Davis" => array ("name" => "Antarctica/Davis" , "country" => "AQ" , "latitude" => "-6835" , "longitude" => "+07758" , "comment" => "Davis Station, Vestfold Hills" ),
"Antarctica/DumontDUrville" => array ("name" => "Antarctica/DumontDUrville" , "country" => "AQ" , "latitude" => "-6640" , "longitude" => "+14001" , "comment" => "Dumont-d'Urville Base, Terre Adelie" ),
"Antarctica/Mawson" => array ("name" => "Antarctica/Mawson" , "country" => "AQ" , "latitude" => "-6736" , "longitude" => "+06253" , "comment" => "Mawson Station, Holme Bay" ),
"Antarctica/McMurdo" => array ("name" => "Antarctica/McMurdo" , "country" => "AQ" , "latitude" => "-7750" , "longitude" => "+16636" , "comment" => "McMurdo Station, Ross Island" ),
"Antarctica/Palmer" => array ("name" => "Antarctica/Palmer" , "country" => "AQ" , "latitude" => "-6448" , "longitude" => "-06406" , "comment" => "Palmer Station, Anvers Island" ),
"Antarctica/South_Pole" => array ("name" => "Antarctica/South_Pole" , "country" => "AQ" , "latitude" => "-9000" , "longitude" => "+00000" , "comment" => "Amundsen-Scott Station, South Pole" ),
"Arctic/Longyearbyen" => array ("name" => "Arctic/Longyearbyen" , "country" => "SJ" , "latitude" => "+7800" , "longitude" => "+01600" , "comment" => "Svalbard" ),
"Asia/Aden" => array ("name" => "Asia/Aden" , "country" => "YE" , "latitude" => "+1245" , "longitude" => "+04512" , "comment" => "" ),
"Asia/Almaty" => array ("name" => "Asia/Almaty" , "country" => "KZ" , "latitude" => "+4315" , "longitude" => "+07657" , "comment" => "east Kazakhstan" ),
"Asia/Amman" => array ("name" => "Asia/Amman" , "country" => "JO" , "latitude" => "+3157" , "longitude" => "+03556" , "comment" => "" ),
"Asia/Anadyr" => array ("name" => "Asia/Anadyr" , "country" => "RU" , "latitude" => "+6445" , "longitude" => "+17729" , "comment" => "Moscow+10 - Bering Sea" ),
"Asia/Aqtau" => array ("name" => "Asia/Aqtau" , "country" => "KZ" , "latitude" => "+4431" , "longitude" => "+05016" , "comment" => "west Kazakhstan" ),
"Asia/Aqtobe" => array ("name" => "Asia/Aqtobe" , "country" => "KZ" , "latitude" => "+5017" , "longitude" => "+05710" , "comment" => "central Kazakhstan" ),
"Asia/Ashkhabad" => array ("name" => "Asia/Ashkhabad" , "country" => "TM" , "latitude" => "+3757" , "longitude" => "+05823" , "comment" => "" ),
"Asia/Baghdad" => array ("name" => "Asia/Baghdad" , "country" => "IQ" , "latitude" => "+3321" , "longitude" => "+04425" , "comment" => "" ),
"Asia/Bahrain" => array ("name" => "Asia/Bahrain" , "country" => "BH" , "latitude" => "+2623" , "longitude" => "+05035" , "comment" => "" ),
"Asia/Baku" => array ("name" => "Asia/Baku" , "country" => "AZ" , "latitude" => "+4023" , "longitude" => "+04951" , "comment" => "" ),
"Asia/Bangkok" => array ("name" => "Asia/Bangkok" , "country" => "TH" , "latitude" => "+1345" , "longitude" => "+10031" , "comment" => "" ),
"Asia/Beirut" => array ("name" => "Asia/Beirut" , "country" => "LB" , "latitude" => "+3353" , "longitude" => "+03530" , "comment" => "" ),
"Asia/Bishkek" => array ("name" => "Asia/Bishkek" , "country" => "KG" , "latitude" => "+4254" , "longitude" => "+07436" , "comment" => "" ),
"Asia/Brunei" => array ("name" => "Asia/Brunei" , "country" => "BN" , "latitude" => "+0456" , "longitude" => "+11455" , "comment" => "" ),
"Asia/Calcutta" => array ("name" => "Asia/Calcutta" , "country" => "IN" , "latitude" => "+2232" , "longitude" => "+08822" , "comment" => "" ),
"Asia/Chungking" => array ("name" => "Asia/Chungking" , "country" => "CN" , "latitude" => "+2934" , "longitude" => "+10635" , "comment" => "China mountains" ),
"Asia/Colombo" => array ("name" => "Asia/Colombo" , "country" => "LK" , "latitude" => "+0656" , "longitude" => "+07951" , "comment" => "" ),
"Asia/Dacca" => array ("name" => "Asia/Dacca" , "country" => "BD" , "latitude" => "+2343" , "longitude" => "+09025" , "comment" => "" ),
"Asia/Damascus" => array ("name" => "Asia/Damascus" , "country" => "SY" , "latitude" => "+3330" , "longitude" => "+03618" , "comment" => "" ),
"Asia/Dubai" => array ("name" => "Asia/Dubai" , "country" => "AE" , "latitude" => "+2518" , "longitude" => "+05518" , "comment" => "" ),
"Asia/Dushanbe" => array ("name" => "Asia/Dushanbe" , "country" => "TJ" , "latitude" => "+3835" , "longitude" => "+06848" , "comment" => "" ),
"Asia/Gaza" => array ("name" => "Asia/Gaza" , "country" => "PS" , "latitude" => "+3130" , "longitude" => "+03428" , "comment" => "" ),
"Asia/Harbin" => array ("name" => "Asia/Harbin" , "country" => "CN" , "latitude" => "+4545" , "longitude" => "+12641" , "comment" => "north Manchuria" ),
"Asia/Hong_Kong" => array ("name" => "Asia/Hong_Kong" , "country" => "CN" , "latitude" => "+2217" , "longitude" => "+11409" , "comment" => "Hong Kong" ),
"Asia/Irkutsk" => array ("name" => "Asia/Irkutsk" , "country" => "RU" , "latitude" => "+5216" , "longitude" => "+10420" , "comment" => "Moscow+05 - Lake Baikal" ),
"Asia/Jakarta" => array ("name" => "Asia/Jakarta" , "country" => "ID" , "latitude" => "-0610" , "longitude" => "+10648" , "comment" => "Java & Sumatra" ),
"Asia/Jayapura" => array ("name" => "Asia/Jayapura" , "country" => "ID" , "latitude" => "-0232" , "longitude" => "+14042" , "comment" => "Irian Jaya & the Moluccas" ),
"Asia/Jerusalem" => array ("name" => "Asia/Jerusalem" , "country" => "IL" , "latitude" => "+3146" , "longitude" => "+03514" , "comment" => "" ),
"Asia/Kabul" => array ("name" => "Asia/Kabul" , "country" => "AF" , "latitude" => "+3431" , "longitude" => "+06912" , "comment" => "" ),
"Asia/Kamchatka" => array ("name" => "Asia/Kamchatka" , "country" => "RU" , "latitude" => "+5301" , "longitude" => "+15839" , "comment" => "Moscow+09 - Kamchatka" ),
"Asia/Karachi" => array ("name" => "Asia/Karachi" , "country" => "PK" , "latitude" => "+2452" , "longitude" => "+06703" , "comment" => "" ),
"Asia/Kashgar" => array ("name" => "Asia/Kashgar" , "country" => "CN" , "latitude" => "+3929" , "longitude" => "+07559" , "comment" => "Eastern Turkestan" ),
"Asia/Katmandu" => array ("name" => "Asia/Katmandu" , "country" => "NP" , "latitude" => "+2743" , "longitude" => "+08519" , "comment" => "" ),
"Asia/Krasnoyarsk" => array ("name" => "Asia/Krasnoyarsk" , "country" => "RU" , "latitude" => "+5601" , "longitude" => "+09250" , "comment" => "Moscow+04 - Yenisei River" ),
"Asia/Kuala_Lumpur" => array ("name" => "Asia/Kuala_Lumpur" , "country" => "MY" , "latitude" => "+0310" , "longitude" => "+10142" , "comment" => "peninsular Malaysia" ),
"Asia/Kuching" => array ("name" => "Asia/Kuching" , "country" => "MY" , "latitude" => "+0133" , "longitude" => "+11020" , "comment" => "Sabah & Sarawak" ),
"Asia/Kuwait" => array ("name" => "Asia/Kuwait" , "country" => "KW" , "latitude" => "+2920" , "longitude" => "+04759" , "comment" => "" ),
"Asia/Macao" => array ("name" => "Asia/Macao" , "country" => "MO" , "latitude" => "+2214" , "longitude" => "+11335" , "comment" => "" ),
"Asia/Magadan" => array ("name" => "Asia/Magadan" , "country" => "RU" , "latitude" => "+5934" , "longitude" => "+15048" , "comment" => "Moscow+08 - Magadan & Sakhalin" ),
"Asia/Manila" => array ("name" => "Asia/Manila" , "country" => "PH" , "latitude" => "+1435" , "longitude" => "+12100" , "comment" => "" ),
"Asia/Muscat" => array ("name" => "Asia/Muscat" , "country" => "OM" , "latitude" => "+2336" , "longitude" => "+05835" , "comment" => "" ),
"Asia/Nicosia" => array ("name" => "Asia/Nicosia" , "country" => "CY" , "latitude" => "+3510" , "longitude" => "+03322" , "comment" => "" ),
"Asia/Novosibirsk" => array ("name" => "Asia/Novosibirsk" , "country" => "RU" , "latitude" => "+5502" , "longitude" => "+08255" , "comment" => "Moscow+03 - Novosibirsk" ),
"Asia/Omsk" => array ("name" => "Asia/Omsk" , "country" => "RU" , "latitude" => "+5500" , "longitude" => "+07324" , "comment" => "Moscow+03 - west Siberia" ),
"Asia/Phnom_Penh" => array ("name" => "Asia/Phnom_Penh" , "country" => "KH" , "latitude" => "+1133" , "longitude" => "+10455" , "comment" => "" ),
"Asia/Pyongyang" => array ("name" => "Asia/Pyongyang" , "country" => "KP" , "latitude" => "+3901" , "longitude" => "+12545" , "comment" => "" ),
"Asia/Qatar" => array ("name" => "Asia/Qatar" , "country" => "QA" , "latitude" => "+2517" , "longitude" => "+05132" , "comment" => "" ),
"Asia/Rangoon" => array ("name" => "Asia/Rangoon" , "country" => "MM" , "latitude" => "+1647" , "longitude" => "+09610" , "comment" => "" ),
"Asia/Riyadh" => array ("name" => "Asia/Riyadh" , "country" => "SA" , "latitude" => "+2438" , "longitude" => "+04643" , "comment" => "" ),
"Asia/Saigon" => array ("name" => "Asia/Saigon" , "country" => "VN" , "latitude" => "+1045" , "longitude" => "+10640" , "comment" => "" ),
"Asia/Samarkand" => array ("name" => "Asia/Samarkand" , "country" => "UZ" , "latitude" => "+3940" , "longitude" => "+06648" , "comment" => "west Uzbekistan" ),
"Asia/Seoul" => array ("name" => "Asia/Seoul" , "country" => "KR" , "latitude" => "+3733" , "longitude" => "+12658" , "comment" => "" ),
"Asia/Shanghai" => array ("name" => "Asia/Shanghai" , "country" => "CN" , "latitude" => "+3114" , "longitude" => "+12128" , "comment" => "China coast" ),
"Asia/Singapore" => array ("name" => "Asia/Singapore" , "country" => "SG" , "latitude" => "+0117" , "longitude" => "+10351" , "comment" => "" ),
"Asia aipei" => array ("name" => "Asia aipei" , "country" => "TW" , "latitude" => "+2503" , "longitude" => "+12130" , "comment" => "" ),
"Asia ashkent" => array ("name" => "Asia ashkent" , "country" => "UZ" , "latitude" => "+4120" , "longitude" => "+06918" , "comment" => "east Uzbekistan" ),
"Asia bilisi" => array ("name" => "Asia bilisi" , "country" => "GE" , "latitude" => "+4143" , "longitude" => "+04449" , "comment" => "" ),
"Asia ehran" => array ("name" => "Asia ehran" , "country" => "IR" , "latitude" => "+3540" , "longitude" => "+05126" , "comment" => "" ),
"Asia himbu" => array ("name" => "Asia himbu" , "country" => "BT" , "latitude" => "+2728" , "longitude" => "+08939" , "comment" => "" ),
"Asia okyo" => array ("name" => "Asia okyo" , "country" => "JP" , "latitude" => "+35391" , "longitude" => "+1394441" , "comment" => "" ),
"Asia/Ujung_Pandang" => array ("name" => "Asia/Ujung_Pandang" , "country" => "ID" , "latitude" => "-0507" , "longitude" => "+11924" , "comment" => "Borneo & Celebes" ),
"Asia/Ulan_Bator" => array ("name" => "Asia/Ulan_Bator" , "country" => "MN" , "latitude" => "+4755" , "longitude" => "+10653" , "comment" => "" ),
"Asia/Urumqi" => array ("name" => "Asia/Urumqi" , "country" => "CN" , "latitude" => "+4348" , "longitude" => "+08735" , "comment" => "Tibet & Xinjiang" ),
"Asia/Vientiane" => array ("name" => "Asia/Vientiane" , "country" => "LA" , "latitude" => "+1758" , "longitude" => "+10236" , "comment" => "" ),
"Asia/Vladivostok" => array ("name" => "Asia/Vladivostok" , "country" => "RU" , "latitude" => "+4310" , "longitude" => "+13156" , "comment" => "Moscow+07 - Amur River" ),
"Asia/Yakutsk" => array ("name" => "Asia/Yakutsk" , "country" => "RU" , "latitude" => "+6200" , "longitude" => "+12940" , "comment" => "Moscow+06 - Lena River" ),
"Asia/Yekaterinburg" => array ("name" => "Asia/Yekaterinburg" , "country" => "RU" , "latitude" => "+5651" , "longitude" => "+06036" , "comment" => "Moscow+02 - Urals" ),
"Asia/Yerevan" => array ("name" => "Asia/Yerevan" , "country" => "AM" , "latitude" => "+4011" , "longitude" => "+04430" , "comment" => "" ),
"Atlantic/Azores" => array ("name" => "Atlantic/Azores" , "country" => "PT" , "latitude" => "+3744" , "longitude" => "-02540" , "comment" => "Azores" ),
"Atlantic/Bermuda" => array ("name" => "Atlantic/Bermuda" , "country" => "BM" , "latitude" => "+3217" , "longitude" => "-06446" , "comment" => "" ),
"Atlantic/Canary" => array ("name" => "Atlantic/Canary" , "country" => "ES" , "latitude" => "+2806" , "longitude" => "-01524" , "comment" => "Canary Islands" ),
"Atlantic/Cape_Verde" => array ("name" => "Atlantic/Cape_Verde" , "country" => "CV" , "latitude" => "+1455" , "longitude" => "-02331" , "comment" => "" ),
"Atlantic/Faeroe" => array ("name" => "Atlantic/Faeroe" , "country" => "FO" , "latitude" => "+6201" , "longitude" => "-00646" , "comment" => "" ),
"Atlantic/Jan_Mayen" => array ("name" => "Atlantic/Jan_Mayen" , "country" => "SJ" , "latitude" => "+7059" , "longitude" => "-00805" , "comment" => "Jan Mayen" ),
"Atlantic/Madeira" => array ("name" => "Atlantic/Madeira" , "country" => "PT" , "latitude" => "+3238" , "longitude" => "-01654" , "comment" => "Madeira Islands" ),
"Atlantic/Reykjavik" => array ("name" => "Atlantic/Reykjavik" , "country" => "IS" , "latitude" => "+6409" , "longitude" => "-02151" , "comment" => "" ),
"Atlantic/South_Georgia" => array ("name" => "Atlantic/South_Georgia" , "country" => "GS" , "latitude" => "-5416" , "longitude" => "-03632" , "comment" => "" ),
"Atlantic/St_Helena" => array ("name" => "Atlantic/St_Helena" , "country" => "SH" , "latitude" => "-1555" , "longitude" => "-00542" , "comment" => "" ),
"Atlantic/Stanley" => array ("name" => "Atlantic/Stanley" , "country" => "FK" , "latitude" => "-5142" , "longitude" => "-05751" , "comment" => "" ),
"Australia/Adelaide" => array ("name" => "Australia/Adelaide" , "country" => "AU" , "latitude" => "-3455" , "longitude" => "+13835" , "comment" => "South Australia" ),
"Australia/Brisbane" => array ("name" => "Australia/Brisbane" , "country" => "AU" , "latitude" => "-2728" , "longitude" => "+15302" , "comment" => "Queensland - most locations" ),
"Australia/Broken_Hill" => array ("name" => "Australia/Broken_Hill" , "country" => "AU" , "latitude" => "-3157" , "longitude" => "+14127" , "comment" => "New South Wales - Broken Hill" ),
"Australia/Darwin" => array ("name" => "Australia/Darwin" , "country" => "AU" , "latitude" => "-1228" , "longitude" => "+13050" , "comment" => "Northern Territory" ),
"Australia/Hobart" => array ("name" => "Australia/Hobart" , "country" => "AU" , "latitude" => "-4253" , "longitude" => "+14719" , "comment" => "Tasmania" ),
"Australia/Lindeman" => array ("name" => "Australia/Lindeman" , "country" => "AU" , "latitude" => "-2016" , "longitude" => "+14900" , "comment" => "Queensland - Holiday Islands" ),
"Australia/Lord_Howe" => array ("name" => "Australia/Lord_Howe" , "country" => "AU" , "latitude" => "-3133" , "longitude" => "+15905" , "comment" => "Lord Howe Island" ),
"Australia/Melbourne" => array ("name" => "Australia/Melbourne" , "country" => "AU" , "latitude" => "-3749" , "longitude" => "+14458" , "comment" => "Victoria" ),
"Australia/Perth" => array ("name" => "Australia/Perth" , "country" => "AU" , "latitude" => "-3157" , "longitude" => "+11551" , "comment" => "Western Australia" ),
"Australia/Sydney" => array ("name" => "Australia/Sydney" , "country" => "AU" , "latitude" => "-3352" , "longitude" => "+15113" , "comment" => "New South Wales - most locations" ),
"Europe/Amsterdam" => array ("name" => "Europe/Amsterdam" , "country" => "NL" , "latitude" => "+5222" , "longitude" => "+00454" , "comment" => "" ),
"Europe/Andorra" => array ("name" => "Europe/Andorra" , "country" => "AD" , "latitude" => "+4230" , "longitude" => "+00131" , "comment" => "" ),
"Europe/Athens" => array ("name" => "Europe/Athens" , "country" => "GR" , "latitude" => "+3758" , "longitude" => "+02343" , "comment" => "" ),
"Europe/Belfast" => array ("name" => "Europe/Belfast" , "country" => "GB" , "latitude" => "+5435" , "longitude" => "-00555" , "comment" => "Northern Ireland" ),
"Europe/Belgrade" => array ("name" => "Europe/Belgrade" , "country" => "YU" , "latitude" => "+4450" , "longitude" => "+02030" , "comment" => "" ),
"Europe/Berlin" => array ("name" => "Europe/Berlin" , "country" => "DE" , "latitude" => "+5230" , "longitude" => "+01322" , "comment" => "" ),
"Europe/Bratislava" => array ("name" => "Europe/Bratislava" , "country" => "SK" , "latitude" => "+4809" , "longitude" => "+01707" , "comment" => "" ),
"Europe/Brussels" => array ("name" => "Europe/Brussels" , "country" => "BE" , "latitude" => "+5050" , "longitude" => "+00420" , "comment" => "" ),
"Europe/Bucharest" => array ("name" => "Europe/Bucharest" , "country" => "RO" , "latitude" => "+4426" , "longitude" => "+02606" , "comment" => "" ),
"Europe/Budapest" => array ("name" => "Europe/Budapest" , "country" => "HU" , "latitude" => "+4730" , "longitude" => "+01905" , "comment" => "" ),
"Europe/Chisinau" => array ("name" => "Europe/Chisinau" , "country" => "MD" , "latitude" => "+4700" , "longitude" => "+02850" , "comment" => "" ),
"Europe/Copenhagen" => array ("name" => "Europe/Copenhagen" , "country" => "DK" , "latitude" => "+5540" , "longitude" => "+01235" , "comment" => "" ),
"Europe/Dublin" => array ("name" => "Europe/Dublin" , "country" => "IE" , "latitude" => "+5320" , "longitude" => "-00615" , "comment" => "" ),
"Europe/Gibraltar" => array ("name" => "Europe/Gibraltar" , "country" => "GI" , "latitude" => "+3608" , "longitude" => "-00521" , "comment" => "" ),
"Europe/Helsinki" => array ("name" => "Europe/Helsinki" , "country" => "FI" , "latitude" => "+6010" , "longitude" => "+02458" , "comment" => "" ),
"Europe/Istanbul" => array ("name" => "Europe/Istanbul" , "country" => "TR" , "latitude" => "+4101" , "longitude" => "+02858" , "comment" => "" ),
"Europe/Kaliningrad" => array ("name" => "Europe/Kaliningrad" , "country" => "RU" , "latitude" => "+5443" , "longitude" => "+02030" , "comment" => "Moscow-01 - Kaliningrad" ),
"Europe/Kiev" => array ("name" => "Europe/Kiev" , "country" => "UA" , "latitude" => "+5026" , "longitude" => "+03031" , "comment" => "most locations" ),
"Europe/Lisbon" => array ("name" => "Europe/Lisbon" , "country" => "PT" , "latitude" => "+3843" , "longitude" => "-00908" , "comment" => "mainland" ),
"Europe/Ljubljana" => array ("name" => "Europe/Ljubljana" , "country" => "SI" , "latitude" => "+4603" , "longitude" => "+01431" , "comment" => "" ),
"Europe/London" => array ("name" => "Europe/London" , "country" => "GB" , "latitude" => "+51283" , "longitude" => "-0001845" , "comment" => "Great Britain" ),
"Europe/Luxembourg" => array ("name" => "Europe/Luxembourg" , "country" => "LU" , "latitude" => "+4936" , "longitude" => "+00609" , "comment" => "" ),
"Europe/Madrid" => array ("name" => "Europe/Madrid" , "country" => "ES" , "latitude" => "+4024" , "longitude" => "-00341" , "comment" => "mainland" ),
"Europe/Malta" => array ("name" => "Europe/Malta" , "country" => "MT" , "latitude" => "+3554" , "longitude" => "+01431" , "comment" => "" ),
"Europe/Minsk" => array ("name" => "Europe/Minsk" , "country" => "BY" , "latitude" => "+5354" , "longitude" => "+02734" , "comment" => "" ),
"Europe/Monaco" => array ("name" => "Europe/Monaco" , "country" => "MC" , "latitude" => "+4342" , "longitude" => "+00723" , "comment" => "" ),
"Europe/Moscow" => array ("name" => "Europe/Moscow" , "country" => "RU" , "latitude" => "+5545" , "longitude" => "+03735" , "comment" => "Moscow+00 - west Russia" ),
"Europe/Oslo" => array ("name" => "Europe/Oslo" , "country" => "NO" , "latitude" => "+5955" , "longitude" => "+01045" , "comment" => "" ),
"Europe/Paris" => array ("name" => "Europe/Paris" , "country" => "FR" , "latitude" => "+4852" , "longitude" => "+00220" , "comment" => "" ),
"Europe/Prague" => array ("name" => "Europe/Prague" , "country" => "CZ" , "latitude" => "+5005" , "longitude" => "+01426" , "comment" => "" ),
"Europe/Riga" => array ("name" => "Europe/Riga" , "country" => "LV" , "latitude" => "+5657" , "longitude" => "+02406" , "comment" => "" ),
"Europe/Rome" => array ("name" => "Europe/Rome" , "country" => "IT" , "latitude" => "+4154" , "longitude" => "+01229" , "comment" => "" ),
"Europe/Samara" => array ("name" => "Europe/Samara" , "country" => "RU" , "latitude" => "+5312" , "longitude" => "+05009" , "comment" => "Moscow+01 - Caspian Sea" ),
"Europe/San_Marino" => array ("name" => "Europe/San_Marino" , "country" => "SM" , "latitude" => "+4355" , "longitude" => "+01228" , "comment" => "" ),
"Europe/Sarajevo" => array ("name" => "Europe/Sarajevo" , "country" => "BA" , "latitude" => "+4352" , "longitude" => "+01825" , "comment" => "" ),
"Europe/Simferopol" => array ("name" => "Europe/Simferopol" , "country" => "UA" , "latitude" => "+4457" , "longitude" => "+03406" , "comment" => "Crimea" ),
"Europe/Skopje" => array ("name" => "Europe/Skopje" , "country" => "MK" , "latitude" => "+4159" , "longitude" => "+02126" , "comment" => "" ),
"Europe/Sofia" => array ("name" => "Europe/Sofia" , "country" => "BG" , "latitude" => "+4241" , "longitude" => "+02319" , "comment" => "" ),
"Europe/Stockholm" => array ("name" => "Europe/Stockholm" , "country" => "SE" , "latitude" => "+5920" , "longitude" => "+01803" , "comment" => "" ),
"Europe allinn" => array ("name" => "Europe allinn" , "country" => "EE" , "latitude" => "+5925" , "longitude" => "+02445" , "comment" => "" ),
"Europe irane" => array ("name" => "Europe irane" , "country" => "AL" , "latitude" => "+4120" , "longitude" => "+01950" , "comment" => "" ),
"Europe/Vaduz" => array ("name" => "Europe/Vaduz" , "country" => "LI" , "latitude" => "+4709" , "longitude" => "+00931" , "comment" => "" ),
"Europe/Vatican" => array ("name" => "Europe/Vatican" , "country" => "VA" , "latitude" => "+4154" , "longitude" => "+01227" , "comment" => "" ),
"Europe/Vienna" => array ("name" => "Europe/Vienna" , "country" => "AT" , "latitude" => "+4813" , "longitude" => "+01620" , "comment" => "" ),
"Europe/Vilnius" => array ("name" => "Europe/Vilnius" , "country" => "LT" , "latitude" => "+5441" , "longitude" => "+02519" , "comment" => "" ),
"Europe/Warsaw" => array ("name" => "Europe/Warsaw" , "country" => "PL" , "latitude" => "+5215" , "longitude" => "+02100" , "comment" => "" ),
"Europe/Zagreb" => array ("name" => "Europe/Zagreb" , "country" => "HR" , "latitude" => "+4548" , "longitude" => "+01558" , "comment" => "" ),
"Europe/Zurich" => array ("name" => "Europe/Zurich" , "country" => "CH" , "latitude" => "+4723" , "longitude" => "+00832" , "comment" => "" ),
"Indian/Antananarivo" => array ("name" => "Indian/Antananarivo" , "country" => "MG" , "latitude" => "-1855" , "longitude" => "+04731" , "comment" => "" ),
"Indian/Chagos" => array ("name" => "Indian/Chagos" , "country" => "IO" , "latitude" => "-0720" , "longitude" => "+07225" , "comment" => "" ),
"Indian/Christmas" => array ("name" => "Indian/Christmas" , "country" => "CX" , "latitude" => "-1025" , "longitude" => "+10543" , "comment" => "" ),
"Indian/Cocos" => array ("name" => "Indian/Cocos" , "country" => "CC" , "latitude" => "-1210" , "longitude" => "+09655" , "comment" => "" ),
"Indian/Comoro" => array ("name" => "Indian/Comoro" , "country" => "KM" , "latitude" => "-1141" , "longitude" => "+04316" , "comment" => "" ),
"Indian/Kerguelen" => array ("name" => "Indian/Kerguelen" , "country" => "TF" , "latitude" => "-49211" , "longitude" => "+0701303" , "comment" => "" ),
"Indian/Mahe" => array ("name" => "Indian/Mahe" , "country" => "SC" , "latitude" => "-0440" , "longitude" => "+05528" , "comment" => "" ),
"Indian/Maldives" => array ("name" => "Indian/Maldives" , "country" => "MV" , "latitude" => "+0410" , "longitude" => "+07330" , "comment" => "" ),
"Indian/Mauritius" => array ("name" => "Indian/Mauritius" , "country" => "MU" , "latitude" => "-2010" , "longitude" => "+05730" , "comment" => "" ),
"Indian/Mayotte" => array ("name" => "Indian/Mayotte" , "country" => "YT" , "latitude" => "-1247" , "longitude" => "+04514" , "comment" => "" ),
"Indian/Reunion" => array ("name" => "Indian/Reunion" , "country" => "RE" , "latitude" => "-2052" , "longitude" => "+05528" , "comment" => "" ),
"Pacific/Apia" => array ("name" => "Pacific/Apia" , "country" => "WS" , "latitude" => "-1350" , "longitude" => "-17144" , "comment" => "" ),
"Pacific/Auckland" => array ("name" => "Pacific/Auckland" , "country" => "NZ" , "latitude" => "-3652" , "longitude" => "+17446" , "comment" => "most locations" ),
"Pacific/Chatham" => array ("name" => "Pacific/Chatham" , "country" => "NZ" , "latitude" => "-4355" , "longitude" => "-17630" , "comment" => "Chatham Islands" ),
"Pacific/Easter" => array ("name" => "Pacific/Easter" , "country" => "CL" , "latitude" => "-2710" , "longitude" => "-10927" , "comment" => "Easter Island" ),
"Pacific/Efate" => array ("name" => "Pacific/Efate" , "country" => "VU" , "latitude" => "-1740" , "longitude" => "+16825" , "comment" => "" ),
"Pacific/Enderbury" => array ("name" => "Pacific/Enderbury" , "country" => "KI" , "latitude" => "-0308" , "longitude" => "-17105" , "comment" => "Phoenix Islands" ),
"Pacific/Fakaofo" => array ("name" => "Pacific/Fakaofo" , "country" => "TK" , "latitude" => "-0922" , "longitude" => "-17114" , "comment" => "" ),
"Pacific/Fiji" => array ("name" => "Pacific/Fiji" , "country" => "FJ" , "latitude" => "-1808" , "longitude" => "+17825" , "comment" => "" ),
"Pacific/Funafuti" => array ("name" => "Pacific/Funafuti" , "country" => "TV" , "latitude" => "-0831" , "longitude" => "+17913" , "comment" => "" ),
"Pacific/Galapagos" => array ("name" => "Pacific/Galapagos" , "country" => "EC" , "latitude" => "-0054" , "longitude" => "-08936" , "comment" => "Galapagos Islands" ),
"Pacific/Gambier" => array ("name" => "Pacific/Gambier" , "country" => "PF" , "latitude" => "-2308" , "longitude" => "-13457" , "comment" => "Gambier Islands" ),
"Pacific/Guadalcanal" => array ("name" => "Pacific/Guadalcanal" , "country" => "SB" , "latitude" => "-0932" , "longitude" => "+16012" , "comment" => "" ),
"Pacific/Guam" => array ("name" => "Pacific/Guam" , "country" => "GU" , "latitude" => "+1328" , "longitude" => "+14445" , "comment" => "" ),
"Pacific/Honolulu" => array ("name" => "Pacific/Honolulu" , "country" => "US" , "latitude" => "+21182" , "longitude" => "-1575130" , "comment" => "Hawaii" ),
"Pacific/Johnston" => array ("name" => "Pacific/Johnston" , "country" => "UM" , "latitude" => "+1700" , "longitude" => "-16830" , "comment" => "Johnston Atoll" ),
"Pacific/Kiritimati" => array ("name" => "Pacific/Kiritimati" , "country" => "KI" , "latitude" => "+0152" , "longitude" => "-15720" , "comment" => "Line Islands" ),
"Pacific/Kosrae" => array ("name" => "Pacific/Kosrae" , "country" => "FM" , "latitude" => "+0519" , "longitude" => "+16259" , "comment" => "Kosrae" ),
"Pacific/Kwajalein" => array ("name" => "Pacific/Kwajalein" , "country" => "MH" , "latitude" => "+0905" , "longitude" => "+16720" , "comment" => "Kwajalein" ),
"Pacific/Majuro" => array ("name" => "Pacific/Majuro" , "country" => "MH" , "latitude" => "+0709" , "longitude" => "+17112" , "comment" => "most locations" ),
"Pacific/Marquesas" => array ("name" => "Pacific/Marquesas" , "country" => "PF" , "latitude" => "-0900" , "longitude" => "-13930" , "comment" => "Marquesas Islands" ),
"Pacific/Midway" => array ("name" => "Pacific/Midway" , "country" => "UM" , "latitude" => "+2813" , "longitude" => "-17722" , "comment" => "Midway Islands" ),
"Pacific/Nauru" => array ("name" => "Pacific/Nauru" , "country" => "NR" , "latitude" => "-0031" , "longitude" => "+16655" , "comment" => "" ),
"Pacific/Niue" => array ("name" => "Pacific/Niue" , "country" => "NU" , "latitude" => "-1901" , "longitude" => "+16955" , "comment" => "" ),
"Pacific/Norfolk" => array ("name" => "Pacific/Norfolk" , "country" => "NF" , "latitude" => "-2903" , "longitude" => "+16758" , "comment" => "" ),
"Pacific/Noumea" => array ("name" => "Pacific/Noumea" , "country" => "NC" , "latitude" => "-2216" , "longitude" => "+16530" , "comment" => "" ),
"Pacific/Pago_Pago" => array ("name" => "Pacific/Pago_Pago" , "country" => "AS" , "latitude" => "-1416" , "longitude" => "-17042" , "comment" => "" ),
"Pacific/Palau" => array ("name" => "Pacific/Palau" , "country" => "PW" , "latitude" => "+0720" , "longitude" => "+13429" , "comment" => "" ),
"Pacific/Pitcairn" => array ("name" => "Pacific/Pitcairn" , "country" => "PN" , "latitude" => "-2504" , "longitude" => "-13005" , "comment" => "" ),
"Pacific/Ponape" => array ("name" => "Pacific/Ponape" , "country" => "FM" , "latitude" => "+0658" , "longitude" => "+15813" , "comment" => "Ponape (Pohnpei)" ),
"Pacific/Port_Moresby" => array ("name" => "Pacific/Port_Moresby" , "country" => "PG" , "latitude" => "-0930" , "longitude" => "+14710" , "comment" => "" ),
"Pacific/Rarotonga" => array ("name" => "Pacific/Rarotonga" , "country" => "CK" , "latitude" => "-2114" , "longitude" => "-15946" , "comment" => "" ),
"Pacific/Saipan" => array ("name" => "Pacific/Saipan" , "country" => "MP" , "latitude" => "+1512" , "longitude" => "+14545" , "comment" => "" ),
"Pacific ahiti" => array ("name" => "Pacific ahiti" , "country" => "PF" , "latitude" => "-1732" , "longitude" => "-14934" , "comment" => "Society Islands" ),
"Pacific arawa" => array ("name" => "Pacific arawa" , "country" => "KI" , "latitude" => "+0125" , "longitude" => "+17300" , "comment" => "Gilbert Islands" ),
"Pacific ongatapu" => array ("name" => "Pacific ongatapu" , "country" => "TO" , "latitude" => "-2110" , "longitude" => "+17510" , "comment" => "" ),
"Pacific ruk" => array ("name" => "Pacific ruk" , "country" => "FM" , "latitude" => "+0725" , "longitude" => "+15147" , "comment" => "Truk (Chuuk)" ),
"Pacific/Wake" => array ("name" => "Pacific/Wake" , "country" => "UM" , "latitude" => "+1917" , "longitude" => "+16637" , "comment" => "Wake Island" ),
"Pacific/Wallis" => array ("name" => "Pacific/Wallis" , "country" => "WF" , "latitude" => "-1318" , "longitude" => "-17610" , "comment" => "" ),
"Pacific/Yap" => array ("name" => "Pacific/Yap" , "country" => "FM" , "latitude" => "+0931" , "longitude" => "+13808" , "comment" => "Yap" )
);           
?>
